# Listar Todas
GET http://localhost:8080/api/task
###

# Apagar
DELETE http://localhost:8080/api/task/1

###

# Cadastrar

POST  http://localhost:8080/api/task/
Content-Type: application/json
Authorization: Basic joao@fiap.com.br 123

{
      "title": "Modelar o BD",
      "description": "Modelar as tabelas do banco",
      "score": 100
}
###

